"""add is_available in Table2

Revision ID: 5ebe09fb3585
Revises: e7f9a7cd7951
Create Date: 2026-02-02 19:58:58.598372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ebe09fb3585'
down_revision: Union[str, Sequence[str], None] = 'e7f9a7cd7951'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tables', sa.Column('is_available', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tables', 'is_available')
    # ### end Alembic commands ###
